name = "crdt"
description = "CRDT library for Ada/SPARK"
version = "1.1.0"
licenses = "MIT"
authors = ["bladeacer"]
maintainers = ["bladeacer <wg.nick.exe@gmail.com>"]
maintainers-logins = ["bladeacer"]
website = "https://github.com/bladeacer/ada_crdt"
tags = ["crdt", "spark", "ada", "library"]
auto-gpr-with = false

[origin]
url = "git+https://github.com/bladeacer/ada_crdt.git"
commit = "a642a4629b518d463eca6c3b9a5e97a33531b088"
