#!/usr/bin/env python3
"""Regenerate the README Quick Reference documentation table.

Each component maps to one generated API doc in docs/api-docs/ whose first
line is the package name (`# CRDT.X`). This script rewrites the
`### Quick Reference` table in README.md from those files, so the table
cannot drift from the generated docs. Run via `make doc` (api-docs target).
Exits non-zero if a referenced API doc is missing or lacks a package header.
"""

import os
import sys

README = "README.md"
API_DIR = "docs/api-docs"

COMPONENTS = [
    ("PN-Counter", "crdt-pn_counters"),
    ("LWW Set (Lamport, **deprecated**)", "crdt-lww_element_sets"),
    ("LWW Set (any clock)", "crdt-lww_sets"),
    ("RGA Sequence", "crdt-rga"),
    ("Clock strategies", "crdt-clocks"),
    ("State-based sync", "crdt-sync-state_based"),
    ("Op-based sync", "crdt-sync-op_based"),
    ("Thread-safe wrappers", "crdt-protected"),
    ("Bounded wrappers", "crdt-bounded"),
    ("HLC", "crdt-hlc"),
]


def package_of(stem):
    path = os.path.join(API_DIR, stem + ".md")
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if line.startswith("# "):
                return line[2:]
    raise RuntimeError("no `# <package>` header in " + path)


def fill_table():
    lines = [
        "",
        "<!-- Generated by tools/gen-quickref.py via make doc. Do not edit by hand. -->",
        "",
        "| Component | Package | API Docs |",
        "|-----------|---------|----------|",
    ]
    for display, stem in COMPONENTS:
        if not os.path.isfile(os.path.join(API_DIR, stem + ".md")):
            sys.stderr.write("gen-quickref: missing %s/%s.md\n" % (API_DIR, stem))
            sys.exit(1)
        lines.append("| %s | `%s` | [docs](%s/%s.md) |" % (display, package_of(stem), API_DIR, stem))
    lines.append("")
    return lines


def main():
    with open(README, "r", encoding="utf-8") as f:
        content = f.readlines()

    start = end = None
    for i, line in enumerate(content):
        if line.rstrip("\n") == "### Quick Reference":
            start = i
        elif start is not None and line.startswith("### "):
            end = i
            break
    if start is None or end is None:
        sys.stderr.write("gen-quickref: cannot find `### Quick Reference` block in %s\n" % README)
        sys.exit(1)

    content[start + 1:end] = [x + "\n" for x in fill_table()]
    with open(README, "w", encoding="utf-8") as f:
        f.writelines(content)
    sys.stdout.write("Regenerated %s Quick Reference table\n" % README)


if __name__ == "__main__":
    main()