#!/usr/bin/env python3
"""
Generate SPARK coverage report page for docs/api-docs/.
Scans all .ads and .adb files for SPARK_Mode => Off annotations
and extracts their justification from surrounding comments.
"""
import os
import re
import sys

SRC_DIR = "src"
OUTPUT = "docs/api-docs/crdt-spark-coverage.md"

def find_spark_off(dirpath):
    """Find all SPARK_Mode => Off occurrences with context."""
    results = []
    for root, dirs, files in os.walk(dirpath):
        dirs.sort()
        for f in sorted(files):
            if not f.endswith((".ads", ".adb")):
                continue
            path = os.path.join(root, f)
            rel = os.path.relpath(path, start=".")
            with open(path, "r", encoding="utf-8") as fp:
                lines = fp.readlines()
            for i, line in enumerate(lines):
                stripped = line.strip()
                if stripped.startswith("--"):
                    continue
                if re.search(r'SPARK_Mode\s*=>\s*Off', stripped):
                    # Gather preceding comments
                    comments = []
                    for j in range(i - 1, max(i - 6, -1), -1):
                        cl = lines[j].strip()
                        if cl.startswith("--") and not cl.startswith("---"):
                            comments.insert(0, cl)
                        elif cl == "":
                            continue
                        else:
                            break
                    justification = ""
                    for cmt in comments:
                        justification += cmt.replace("--", "").strip() + " "
                    justification = justification.strip()
                    results.append({
                        "file": rel,
                        "line": i + 1,
                        "text": stripped,
                        "justification": justification or "(no comment)",
                        "kind": "body" if f.endswith(".adb") else "spec",
                    })
    return results


def public_private_breakdown(dirpath):
    """Count public vs private entities in .ads files."""
    counts = {"public": 0, "private": 0}
    details = {"public": [], "private": []}
    for root, dirs, files in os.walk(dirpath):
        dirs.sort()
        for f in sorted(files):
            if not f.endswith(".ads"):
                continue
            path = os.path.join(root, f)
            rel = os.path.relpath(path, start=".")
            with open(path, "r", encoding="utf-8") as fp:
                content = fp.read()
            # Simple heuristic: count subprogram declarations before/after "private"
            parts = content.split("\nprivate\n")
            # Also handle "private" with trailing text
            parts2 = content.split("\nprivate")
            if len(parts2) == 1:
                pub = content
                priv = ""
            else:
                pub = parts2[0]
                priv = parts2[-1].lstrip("\n")
            # Count function/procedure declarations (rough)
            pub_count = len(re.findall(r'\b(procedure|function)\s+\w+', pub))
            priv_count = len(re.findall(r'\b(procedure|function)\s+\w+', priv))
            # Exclude test files from breakdown
            if "test_" not in rel:
                counts["public"] += pub_count
                counts["private"] += priv_count
                details["public"].append(f"  - `{rel}`: {pub_count} subprograms")
                details["private"].append(f"  - `{rel}`: {priv_count} subprograms")
    return counts, details


def parse_gnatprove_stats(prove_out):
    """Parse SPARK proof stats from gnatprove.out if available."""
    stats = {"total": "?", "proved": "?", "justified": "?", "unproved": "?"}
    if not os.path.isfile(prove_out):
        return stats
    with open(prove_out, "r", encoding="utf-8") as fp:
        content = fp.read()
    m = re.search(r'^Total\s+(\d+)\s+.*?(\d+)\s+(\d+)\s+(\d+)', content, re.MULTILINE)
    if m:
        stats["total"] = m.group(1)
        stats["proved"] = m.group(2)
        stats["justified"] = m.group(3)
        stats["unproved"] = m.group(4)
    return stats


def main():
    items = find_spark_off(SRC_DIR)
    counts, details = public_private_breakdown(SRC_DIR)
    sp = parse_gnatprove_stats("obj/gnatprove/gnatprove.out")
    lines = []
    lines.append("# CRDT SPARK Coverage Report")
    lines.append("")
    lines.append("Auto-generated by `tools/gen-coverage.py` via `make doc`.")
    lines.append("")
    lines.append("## SPARK_Mode => On (by package spec)")
    lines.append("")
    lines.append("All core specs use `SPARK_Mode` (On) at package level. "
                 "The following packages have scoped `SPARK_Mode => Off` "
                 "on individual subprograms or bodies:")
    lines.append("")

    # Group by file
    by_file = {}
    for item in items:
        by_file.setdefault(item["file"], []).append(item)

    for fname in sorted(by_file.keys()):
        entries = by_file[fname]
        lines.append(f"### `{fname}`")
        lines.append("")
        for e in entries:
            just = e["justification"]
            lines.append(f"- Line {e['line']}: `{e['text']}`")
            if just and just != "(no comment)":
                lines.append(f"  - Justification: {just}")
            lines.append("")
        lines.append("")

    lines.append("## Public vs Private Interface Count")
    lines.append("")
    lines.append(f"- Public subprograms: **{counts['public']}**")
    lines.append(f"- Private subprograms: **{counts['private']}**")
    lines.append("")
    lines.append("### Per-package breakdown")
    lines.append("")
    lines.append("#### Public")
    for d in details["public"]:
        lines.append(d)
    lines.append("")
    lines.append("#### Private")
    for d in details["private"]:
        lines.append(d)
    lines.append("")

    lines.append("## Unproved Status")
    lines.append("")
    if sp["total"] != "?":
        lines.append(f"- **{sp['total']} total SPARK checks**: {sp['proved']} proved, {sp['justified']} justified, {sp['unproved']} unproved")
    else:
        lines.append("- **SPARK checks**: (run `make prove` to populate gnatprove.out)")
    lines.append("- Run `alr gnatprove` or `make prove` to regenerate.")
    lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as fp:
        fp.write("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
